### PR TITLE
Use awk instead of sed for cross-platform compatibility

### LINKED ISSUE #34: Running `make [servicename]` on macOS doesn't generate correct Dockerfile
When I run `./generate phpmyadmin` on my Mac, the resulting Dockerfile looks like this:

```Dockerfile
FROM phpmyadmin/phpmyadmin:4.7.9-1

USER root

RUN apk add --no-cache bash git openssh-client runit

HEALTHCHECK CMD /usr/bin/nc -z 127.0.0.1 80

RUN mkdir -p /etc/service/phpmyadminnCOPY run /etc/service/phpmyadmin/run

CMD ["/sbin/runsvdir", "-P", "/etc/service"]
```

Note this line in particular:

```Dockerfile
RUN mkdir -p /etc/service/phpmyadminnCOPY run /etc/service/phpmyadmin/run
```

This is happening due to the \n newline not getting parsed properly with sed:

```
$ RUN="FOO\nBAR"

$ echo "{{RUN}}" | sed "s|{{RUN}}|${RUN}|g"
FOOnBAR
```

See https://superuser.com/questions/307165/newlines-in-sed-on-mac-os-x.

This works:

```
$ RUN="FOO\\"$'\n'"BAR"

$ echo "{{RUN}}" | sed "s|{{RUN}}|${RUN}|g"
FOO
BAR
```

### PR DESCRIPTION
**Pull request by q0rban**
Resolves #34

### CODE REVIEW

**Comment by q0rban** [comment]
@deviantintegral

**Comment by q0rban** [comment]
Not sure if this is the same issue that you were running into it but it reminded me of this PR.

**Comment by deviantintegral** [comment]
... I completely forgot about the makefile.

In the other PR, I suggested moving to perl for better cross-platform compatibility. Given the sed calls here, perhaps that's worth it?

_or_ go really meta, and build a Dockerfile and require docker-in-docker to build images.

**Comment by q0rban** [comment]
Closing in favor of #99

**Pull request closed without merging**
