### PR TITLE
Ruby service

### PR DESCRIPTION
**Pull request by njt1982**
Seems to build in vagrant...

### CODE REVIEW

**Comment by njt1982** [comment]
https://github.com/TugboatQA/images/blob/abcf0e3fad6086b4c35a5e78cb97f75439c596b5/generate#L19

Why is alpine excluded during generate? It'd be nice to have more lightweight base images... Plus in my project, the ImageMagick build on debian/ubuntu has bugs in it which are not present in Alpine.

**Comment by njt1982** [comment]
I manually ran the generate/build/tags scripts (as I think the makefile would?) and it produced this for `TAGS.md`

---

## Supported Tags for tugboatqa/ruby

* `3.0.1-buster`, `3.0-buster`, `3-buster`, `buster`, `3.0.1`, `3.0`, `3`, `latest`
* `2.7.3-buster`, `2.7-buster`, `2-buster`, `2.7.3`, `2.7`, `2`
* `2.6.7-stretch`, `2.6-stretch`
* `2.6.7-buster`, `2.6-buster`, `2.6.7`, `2.6`
* `2.5.9-stretch`, `2.5-stretch`
* `2.5.9-buster`, `2.5-buster`, `2.5.9`, `2.5`

The above tags are currently supported. Visit https://hub.docker.com/r/tugboatqa/ruby/tags/ to see a list of all available tags for this image, including those that are no longer supported.

**Comment by njt1982** [comment]
Let me know if you want me to revert 0861829

---

## Supported Tags for tugboatqa/ruby

* `3.0.1-buster`, `3.0-buster`, `3-buster`, `buster`, `3.0.1`, `3.0`, `3`, `latest`
* `3.0.1-alpine3.13`, `3.0-alpine3.13`, `3-alpine3.13`, `alpine3.13`, `3.0.1-alpine`, `3.0-alpine`, `3-alpine`, `alpine`
* `3.0.1-alpine3.12`, `3.0-alpine3.12`, `3-alpine3.12`, `alpine3.12`
* `2.7.3-buster`, `2.7-buster`, `2-buster`, `2.7.3`, `2.7`, `2`
* `2.7.3-alpine3.13`, `2.7-alpine3.13`, `2-alpine3.13`, `2.7.3-alpine`, `2.7-alpine`, `2-alpine`
* `2.7.3-alpine3.12`, `2.7-alpine3.12`, `2-alpine3.12`
* `2.6.7-stretch`, `2.6-stretch`
* `2.6.7-buster`, `2.6-buster`, `2.6.7`, `2.6`
* `2.6.7-alpine3.13`, `2.6-alpine3.13`, `2.6.7-alpine`, `2.6-alpine`
* `2.6.7-alpine3.12`, `2.6-alpine3.12`
* `2.5.9-stretch`, `2.5-stretch`
* `2.5.9-buster`, `2.5-buster`, `2.5.9`, `2.5`
* `2.5.9-alpine3.13`, `2.5-alpine3.13`, `2.5.9-alpine`, `2.5-alpine`
* `2.5.9-alpine3.12`, `2.5-alpine3.12`

The above tags are currently supported. Visit https://hub.docker.com/r/tugboatqa/ruby/tags/ to see a list of all available tags for this image, including those that are no longer supported.

**Comment by q0rban** [comment]
@njt1982 thank you so much for working on this! I'm picking it up now.

> Why is alpine excluded during generate? It'd be nice to have more lightweight base images... Plus in my project, the ImageMagick build on debian/ubuntu has bugs in it which are not present in Alpine.

The reason Alpine isn't included isn't well documented, but you can find some details here: TugboatQA/docs#162

With Tugboat's disk-usage efficiencies due to Base Previews, the benefit of avoiding theses hard to debug alpine edge cases outweighs the necessity of having smaller images. That said, so long as the ruby image works with alpine on tugboat, there's no reason to avoid them.

**Comment by q0rban** [comment]
@njt1982 could we start with #67 and then work on alpine tags separately if that doesn't work for your needs?

**Comment by q0rban** [comment]
I went ahead and merged #67 and kicked off a build. Let's see how far this gets us and then we can re-evaluate the need for Alpine. I _really_ appreciate all the work you've done in here and please do not take it as a wasted effort.

**Comment by njt1982** [comment]
It's fine, honest. _goes and sobs in the corner_

At least #67 moves Ruby support forward. I appreciate that including Alpine also required support for it at your end.

Maybe you could make it clear in the docs that Alpine is not recommended and unsupported?! (although that wont stop people (including me!) asking questions on it..)

**Pull request closed without merging**
